#pragma once

#define THREAD_NUM 1

//#define USE_TIME_LIMIT
#define DEFAULT_MAX_TIMES 250000
#define DEFAULT_TIME_LIMIT 1

#define DEFAULT_EXPLORATION_PARAMETER 12

//#define MULTIPLE_SAMPLINGS
#ifdef MULTIPLE_SAMPLINGS
#define SAMPLING_THRESHOLD 0.005
#define SAMPLING_SCALE 5
#define SAMPLING_TIME_LIMIT 4
#endif